function build_cassandra_model()
% BUILD_CASSANDRA_MODEL Programmatically create cassandra_model.slx.
%
%   Two-phase: hint accumulation during outage, burst replay + cascade on return.

    model = 'cassandra_model';

    if bdIsLoaded(model), close_system(model, 0); end
    if exist([model '.slx'], 'file'), delete([model '.slx']); end
    new_system(model);
    open_system(model);

    p = cassandra_params();

    % Store parameters in the model's workspace so Simulink blocks can access them
    hws = get_param(model, 'ModelWorkspace');
    hws.assignin('write_rate', p.write_rate);
    hws.assignin('read_rate', p.read_rate);
    hws.assignin('T_outage', p.T_outage);
    hws.assignin('replay_throttle', p.replay_throttle);
    hws.assignin('D_total', p.D_total);
    hws.assignin('D_normal', p.D_normal);
    hws.assignin('base_latency', p.base_latency);
    hws.assignin('read_timeout', p.read_timeout);
    hws.assignin('repair_cost', p.repair_cost);

    %% Core dynamics — MATLAB Function block
    % MATLAB Function block contains the two-phase Cassandra dynamics:
    % hints accumulate during outage (phase 1), then replay burst +
    % potential cascade on return (phase 2).
    add_block('simulink/User-Defined Functions/MATLAB Function', ...
        [model '/Cassandra_Dynamics'], ...
        'Position', [200 50 450 200]);

    % Access the Stateflow chart backing the MATLAB Function block to set its code
    mf = find(slroot, '-isa', 'Stateflow.EMChart', 'Path', [model '/Cassandra_Dynamics']);
    mf.Script = sprintf([...
        'function [hints, disk_util, read_lat, repair_rate, rho_G, h_disk] = Cassandra_Dynamics(t, hints_prev, repair_prev)\n' ...
        'persistent accumulated_hints\n' ...
        'if isempty(accumulated_hints), accumulated_hints = 0; end\n' ...
        '\n' ...
        'write_rate = %g; read_rate = %g; T_outage = %g;\n' ...
        'replay_throttle = %g;\n' ...
        'D_total = %g; D_normal = %g;\n' ...
        'base_latency = %g; read_timeout = %g;\n' ...
        'repair_cost = %g;\n' ...
        '\n' ...
        '%% Phase 1: Outage — hints accumulate\n' ...
        'if t < T_outage\n' ...
        '    accumulated_hints = accumulated_hints + write_rate * 0.1;  %% dt=0.1\n' ...
        '    replay_iops = 0;\n' ...
        'else\n' ...
        '    %% Phase 2: Replay\n' ...
        '    replay_iops = min(replay_throttle, accumulated_hints / 0.1);\n' ...
        '    accumulated_hints = max(0, accumulated_hints - replay_iops * 0.1);\n' ...
        'end\n' ...
        'hints = accumulated_hints;\n' ...
        '\n' ...
        '%% Disk utilization\n' ...
        'total_iops = D_normal + replay_iops + repair_prev * repair_cost;\n' ...
        'disk_util = min(total_iops / D_total, 0.999);\n' ...
        '\n' ...
        '%% Read latency (M/M/1)\n' ...
        'read_lat = base_latency / (1 - disk_util);\n' ...
        '\n' ...
        '%% Read repair rate\n' ...
        'if read_lat > read_timeout\n' ...
        '    timeout_frac = min(1, (read_lat - read_timeout) / read_lat);\n' ...
        'else\n' ...
        '    timeout_frac = 0;\n' ...
        'end\n' ...
        'repair_rate = read_rate * timeout_frac;\n' ...
        '\n' ...
        '%% Headroom\n' ...
        'h_disk = D_total - total_iops;\n' ...
        '\n' ...
        '%% Gain (scalar, disk-dominated)\n' ...
        '%% Derived from chain rule through M/M/1:\n' ...
        '%%   g = c_r * r_r * tau / (b * D_t)\n' ...
        '%% This gain applies only above u* = 1 - b/tau.\n' ...
        '%% Below u*, gain = 0 (no timeouts, no feedback).\n' ...
        'u_star = 1 - base_latency / read_timeout;\n' ...
        'if disk_util > u_star\n' ...
        '    rho_G = repair_cost * read_rate * read_timeout / (base_latency * D_total);\n' ...
        'else\n' ...
        '    rho_G = 0;\n' ...
        'end\n'], ...
        p.write_rate, p.read_rate, p.T_outage, p.replay_throttle, ...
        p.D_total, p.D_normal, p.base_latency, p.read_timeout, p.repair_cost);

    %% Clock
    % Clock block outputs simulation time — feeds into dynamics so we know when outage ends
    add_block('simulink/Sources/Clock', [model '/Clock'], ...
        'Position', [50 80 80 110]);

    %% Feedback delays
    % Unit Delay blocks carry values across timesteps (like shift registers).
    % These create the feedback loop: previous hints and repair rate feed back
    % into next timestep's computation.
    add_block('simulink/Discrete/Unit Delay', [model '/hints_delay'], ...
        'InitialCondition', '0', 'SampleTime', '0.1', ...
        'Position', [500 250 550 280]);
    add_block('simulink/Discrete/Unit Delay', [model '/repair_delay'], ...
        'InitialCondition', '0', 'SampleTime', '0.1', ...
        'Position', [500 310 550 340]);

    %% To Workspace blocks
    % Cell array of output names — cell arrays use {} and can hold strings of
    % different lengths (unlike regular arrays). This loop programmatically
    % creates To Workspace blocks for each output.
    outputs = {'hints', 'disk_util', 'read_lat', 'repair_rate', 'rho_G', 'h_disk'};
    var_names = {'cass_hints', 'cass_disk_util', 'cass_read_lat', 'cass_repair_rate', 'cass_rho', 'cass_h_disk'};
    for i = 1:numel(outputs)
        add_block('simulink/Sinks/To Workspace', [model '/' outputs{i} '_out'], ...
            'VariableName', var_names{i}, ...
            'Position', [600 30+50*(i-1) 650 60+50*(i-1)]);
    end

    %% Scopes
    add_block('simulink/Sinks/Scope', [model '/cascade_scope'], ...
        'Position', [600 350 630 380], 'NumInputPorts', '3');

    %% Wiring
    % Wire the blocks together. add_line(model, 'Source/port', 'Dest/port') draws a signal line.
    add_line(model, 'Clock/1', 'Cassandra_Dynamics/1');
    add_line(model, 'hints_delay/1', 'Cassandra_Dynamics/2');
    add_line(model, 'repair_delay/1', 'Cassandra_Dynamics/3');

    % sprintf with %d formats the port number. numel() returns number of elements in the cell array.
    for i = 1:numel(outputs)
        add_line(model, sprintf('Cassandra_Dynamics/%d', i), [outputs{i} '_out/1']);
    end

    add_line(model, 'Cassandra_Dynamics/1', 'hints_delay/1');
    add_line(model, 'Cassandra_Dynamics/4', 'repair_delay/1');

    add_line(model, 'Cassandra_Dynamics/2', 'cascade_scope/1');
    add_line(model, 'Cassandra_Dynamics/5', 'cascade_scope/2');
    add_line(model, 'Cassandra_Dynamics/4', 'cascade_scope/3');

    %% Simulation settings
    set_param(model, 'StopTime', num2str(p.sim_time));
    set_param(model, 'SolverType', 'Fixed-step');
    set_param(model, 'FixedStep', '0.1');

    save_system(model, fullfile('models', [model '.slx']));
    fprintf('Created models/%s.slx\n', model);
end
